version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mealmaster_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=mealmaster
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

